apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
data:


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: roboshop
  labels:
    project: roboshop
    component: payment
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      labels:
        project: roboshop
        component: payment
        tier: backend
  template:
    metadata:
      labels:
        project: roboshop
        component: payment
        tier: backend
    spec:
      containers:
      - name: payment
        image: vinaydocker25/payment:v1
        