apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
  namespace: roboshop
  labels:
    project: roboshop
    component: cart
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: cart
      tier: backend
  template:
    metadata:
      labels:
        project: roboshop
        component: cart
        tier: backend
    spec:
      containers:
      - name: cart
        image: vinaydocker25/cart-optimized:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: cart
        ports:  # like EXPOSE just for information
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
---
# service to connect to cart pod
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: cart
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080 
